name: deploy

on:
    push:
    workflow_dispatch:
    schedule:
        - cron: "55 4 * * *"  


jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                  submodules: true
                  fetch-depth: 0

            - name: Update README
              run: |
                  python3 build.py

            - name: Commit and push if changed
              env:
                  personal_token: ${{ secrets.PERSONAL_TOKEN }}
              run: |-
                  git diff
                  git config --global user.email "action@github.com"
                  git config --global user.name "GitHub Action"
                  git add -A
                  git commit -m "ci: update about page (automatically)" || exit 0
                  git push
                  
            - name: Setup Hugo
              uses: peaceiris/actions-hugo@v2
              with:
                  hugo-version: "0.99.1"

            - name: Build Web
              run: hugo

            - name: Deploy Web
              uses: peaceiris/actions-gh-pages@v3
              with:
                  personal_token: ${{ secrets.PERSONAL_TOKEN }}
                  external_repository: trillionze/trillionze
                  publish_branch: trillionze
                  publish_dir: ./public
                  commit_message: ${{ github.event.head_commit.message }}

